In [ ]:
import numpy as np

In [ ]:
a=np.array([1,2,3], dtype="int8")           #dtype is optional
print(a)

In [ ]:
b=np.array([[9, 8.0, 4, 6.9], [1, 3.0, 5, 7]], dtype="float32")
print(b)

In [ ]:
#Get Dimensions
print(a.ndim)
print(b.ndim)

In [ ]:
#Get Shape
print(a.shape)
print(b.shape)

In [ ]:
#Get Type
print(a.dtype)
print(b.dtype)

In [ ]:
#Get Size
print(a.itemsize)           # 1 as int8 uses 1 byte
print(b.itemsize)           # 4 as float32 uses 4 bytes 

Accessing/Changing specific elements, rows, columns, etc.

In [ ]:
a=np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

In [ ]:
#Get a specific element [r, c]
print(a[1,3])           #2nd row, 4th column element 
print(a[-2, 5])         #2nd last row, 6th column element

In [ ]:
#Get a specific row
print(a[0,:])

In [ ]:
#Get a specific column
print(a[:, 3])

In [ ]:
# Getting every 2nd element between 3rd and 6th element
print(a[2:6:2])

In [ ]:
#Reassigning a[0, 0] to 12
a[0, 0]=12
print(a)

In [ ]:
b=np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(b)

In [ ]:
#Getting specific elements
print(b[0,1,1])
print(b[:,1,:])

Initializing Differen Types of Arrays

In [ ]:
#All 0s matrix
x=np.zeros((2,3))
print(x)

In [ ]:
#All 1st matrix
y=np.ones((2,3,5), dtype='int32')
print(y)

In [ ]:
#Any Other Number
z=np.full((2,2), 9)
print(z)

In [ ]:
#Random Decimal Matrix
np.random.rand(4,2, 3)

In [ ]:
#Random Integer Matrix
np.random.randint(2, 8, size=(4,4))

In [ ]:
#Identity Matrix
np.identity(3)

In [ ]:
#Some tricks
output=np.ones((5,5))
print(output)

z=np.zeros((3,3))
z[1,1]=9
print(z)

output[1:4, 1:4]=z
print(output)

In [ ]:
#Be careful while copying arrays!
a=np.array([1,2,3])
b=a
b[0]=100

print(a)            # a[0] also becomes 100

In [ ]:
#To avoid what happened above
a=np.array([1,2,3])
b=a.copy()
b[0]=100

Mathematics

In [ ]:
a=np.array([1,2,3,4])
print(a)

In [ ]:
print(a)
a+=2
print(a)

In [ ]:
a-=2
print(a)

In [ ]:
a*=2
print(a)

In [ ]:
a=a/2
print(a)

In [ ]:
b=np.array([1,0,1,0])
print(a+b)

In [ ]:
a=a**2
print(a)

In [ ]:
#Taking the sine of all values
np.sin(a)
print(a)

Linear Algebra

In [ ]:
a=np.ones((2,3))
print(a)

b=np.full((3,2),2)
print(b)

In [ ]:
#Matrix Multiplication
ans=np.matmul(a,b)
print(ans)

In [ ]:
#Finding the determinant
c=np.identity(3)
np.linalg.det(c)

Statistics

In [ ]:
stats=np.array([[1,2,3], [4,5,6]])
print(stats)

In [ ]:
#Minimum and maximum elements
print(np.min(stats))
print(np.min(stats, axis=0))        #Minimum row
print(np.min(stats, axis=1))        #Minimum column

print(np.max(stats))
print(np.max(stats, axis=0))        #Maximum row
print(np.max(stats, axis=1))        #Maximum column

Reorganizing Arrays

In [ ]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after=before.reshape((2,2,2))
print(after)

In [ ]:
#Vertically Stacking Arrays
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
x=np.vstack([v1,v2,v1,v2])
print(x)

In [ ]:
#Horizontally Stacking Arrays
h1=np.zeros((2,4))
h2=np.ones((2,2))
print(h1)
print(h2)
x=np.hstack([h1,h2])
print(x)

Miscellaneous

In [ ]:
#Load data from file
filedata=np.genfromtxt('data.txt',delimiter=',')
filedata=filedata.astype('int32')
print(filedata)

In [51]:
#Boolean Masking
a=np.array([2,49,59,1,54])
print(a>50)

[False False  True False  True]


In [53]:
#Indexing with a list
a=np.array([1,2,3,4,5,6,7,8,9])
print(a[[2,5,6]])

[3 6 7]


In [66]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(f"{a}\n")
print(a[[0,1,2],[1,2,3]])
print("\n")
print(a[[0,2,3],2:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[ 2  7 12]


[[ 3  4]
 [11 12]
 [15 16]]
